# openmax
PREFERRED_PROVIDER_virtual/openmax-il =		"meta-tiopenmax-24-modular"
PREFERRED_VERSION_tiopenmax-core =		"24.0.11"
PREFERRED_VERSION_tiopenmax-osal =		"24.0.11"
PREFERRED_VERSION_tiopenmax-base =		"24.0.11"
PREFERRED_VERSION_tiopenmax-base2 =		"24.0.11"
PREFERRED_VERSION_tiopenmax-lcml =		"23.5.0.10"
PREFERRED_VERSION_tiopenmax-audiodecode =       "24.0.11"
PREFERRED_VERSION_tiopenmax-audioencode =       "24.0.11"
PREFERRED_VERSION_tiopenmax-common =            "23.5.0.10"
PREFERRED_VERSION_tiopenmax-rmproxy =           "23.5.0.10"
PREFERRED_VERSION_tiopenmax-videodec =          "23.5.0.10"
PREFERRED_VERSION_tiopenmax-videoenc =          "23.5.0.10"

