# omap3430 SDP specific versions

# baseport
PREFERRED_VERSION_x-load =             "4.62"
PREFERRED_VERSION_u-boot =             "5.10"
PREFERRED_VERSION_linux-tiomap =       "2.6.24.7-5.25-P1"

# bridge and friends
PREFERRED_VERSION_tidspbridge-lib =             "23.17-P1"
PREFERRED_VERSION_tidspbridge-module =          "23.17-P1"
PREFERRED_PROVIDER_virtual/dspbridge-driver = "tidspbridge-module"

# tiopenmax
PREFERRED_VERSION_mm-isp =			"1.15"
